# Generated by Django 2.2.12 on 2020-05-10 12:30

from django.db import migrations
import question_manage.listfield


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0002_auto_20200510_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='answer',
            field=question_manage.listfield.ListField(default=[]),
        ),
    ]
