# Generated by Django 2.2.12 on 2020-05-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0005_auto_20200510_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField(default=0)),
                ('ans', models.CharField(max_length=5, verbose_name='选项')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_manage.Grade')),
            ],
            options={
                'verbose_name_plural': '试卷选项',
                'verbose_name': '试卷选项',
                'db_table': 'answer',
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
