# Generated by Django 2.2.12 on 2020-05-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0006_auto_20200510_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanswer',
            name='qid',
        ),
        migrations.AddField(
            model_name='tanswer',
            name='qid',
            field=models.ManyToManyField(to='question_manage.Question'),
        ),
    ]
