# Generated by Django 2.2.12 on 2020-05-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0008_auto_20200510_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='rewind',
            field=models.TextField(default=''),
        ),
    ]
