# Generated by Django 2.2.12 on 2020-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0010_discussion_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': '回复', 'verbose_name_plural': '回复'},
        ),
        migrations.AddField(
            model_name='discussion',
            name='solved',
            field=models.BooleanField(default='False'),
        ),
    ]
