# Generated by Django 2.2.12 on 2020-05-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0011_auto_20200517_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
