# Generated by Django 2.2.12 on 2020-05-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0012_paper_is_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='is_auto',
        ),
        migrations.CreateModel(
            name='AutoPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
                ('generate_time', models.DateField()),
                ('scores', models.IntegerField(verbose_name='总分')),
                ('sum', models.IntegerField(verbose_name='题数')),
                ('qid', models.ManyToManyField(to='question_manage.Question')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_manage.UserEx')),
            ],
            options={
                'verbose_name': '自动生成试卷',
                'verbose_name_plural': '自动生成试卷',
                'db_table': 'autopaper',
            },
        ),
    ]
