# Generated by Django 2.2.12 on 2020-05-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0013_auto_20200524_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopaper',
            name='title',
            field=models.CharField(default='', max_length=20, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='autopaper',
            name='generate_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
