# Generated by Django 2.2.12 on 2020-05-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0014_auto_20200524_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoGrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_manage.AutoPaper')),
                ('sid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='question_manage.UserEx')),
            ],
            options={
                'db_table': 'autograde',
                'verbose_name_plural': '模拟成绩',
                'verbose_name': '模拟成绩',
            },
        ),
        migrations.CreateModel(
            name='AutoTAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=5, verbose_name='选项')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_manage.AutoGrade')),
                ('qid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='question_manage.Question')),
            ],
            options={
                'db_table': 'autoanswer',
                'verbose_name_plural': '模拟试卷选项',
                'verbose_name': '模拟试卷选项',
            },
        ),
    ]
