# Generated by Django 2.2.12 on 2020-05-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0015_autograde_autotanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(default='无', verbose_name='解析'),
        ),
    ]
