# Generated by Django 2.2.12 on 2020-05-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0017_fillin_shortanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shortanswer',
        ),
        migrations.AddField(
            model_name='discussion',
            name='replied',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='fillin',
            name='type',
            field=models.CharField(choices=[('f', '填空题'), ('sa', '简答题')], default='', max_length=10, verbose_name='类型'),
        ),
    ]
