# Generated by Django 2.2.12 on 2020-06-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0021_auto_20200601_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autotanswer',
            options={'verbose_name': '模拟答卷单选题', 'verbose_name_plural': '模拟答卷单选题'},
        ),
        migrations.CreateModel(
            name='F_AutoTAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.TextField(verbose_name='答案')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_manage.AutoGrade')),
                ('qid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='question_manage.Fillin')),
            ],
            options={
                'verbose_name_plural': '模拟答卷填空题',
                'verbose_name': '模拟答卷填空题',
                'db_table': 'f_autoanswer',
            },
        ),
    ]
