# Generated by Django 2.2.12 on 2020-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manage', '0023_auto_20200601_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_tanswer',
            name='rewind',
            field=models.TextField(default='', verbose_name='点评'),
        ),
        migrations.AddField(
            model_name='tanswer',
            name='rewind',
            field=models.TextField(default='', verbose_name='点评'),
        ),
    ]
